"""
Learner memory safety, privacy guardrails, and lifecycle boundary helpers.

Phase 1, Section 13, Part 4.

PURPOSE
-------
Parts 1–3 established what learner memory stores, how evidence accumulates, and
how stored signals are assembled into bounded tutor hints.

Part 4 defines the SAFETY and LIFECYCLE side:
  - What content is FORBIDDEN from entering learner memory, regardless of source
  - How learner memory can be RESET at different scopes
  - How learner memory can be DELETED (hard delete, for account closure/GDPR)
  - Explicit, testable code-level guardrails that operate INDEPENDENTLY of prompt wording

CHILD SAFETY RATIONALE
-----------------------
This platform serves children. Learner memory must never accumulate:
  - Medical or educational diagnoses (ADHD, autism, dyslexia, etc.)
  - Psychological or psychiatric claims (anxiety disorder, depression, PTSD, etc.)
  - Ability-ranking or derogatory language (stupid, slow learner, unteachable, etc.)
  - Engagement manipulation signals (addiction scoring, dopamine loop metrics, etc.)

These guardrails apply to ALL text fields in memory observations, regardless of
whether the content was generated by an AI, input by a teacher, or produced by any
other means. The platform cannot rely on prompt wording alone — the restriction
must be in code.

SAFE CONTENT EXAMPLES (these ARE permitted):
  - "fractions > mixed numbers" (curriculum topic)
  - "confuses numerator with denominator" (specific factual misconception)
  - "asked for step-by-step explanation three times" (style signal)
  - "re-explained photosynthesis repeatedly in one session" (friction signal)

UNSAFE CONTENT EXAMPLES (these ARE BLOCKED):
  - "student has ADHD" — diagnostic label
  - "shows anxiety disorder symptoms" — psychological claim
  - "slow learner who struggles" — ability ranking
  - "may have dyslexia" — speculative diagnostic label

RESET vs DELETE
---------------
  reset_memory(scope=TOPIC_SIGNALS) — clear topic signals, preserve preferences
  reset_memory(scope=PREFERENCES)   — clear style/pace, preserve topic signals
  reset_memory(scope=FRICTION)      — clear recent friction notes
  reset_memory(scope=SESSION_PENDING) — discard session-local unpromotable observations
  reset_memory(scope=ALL)           — clear all memory signals (slice still exists in store)
  delete_user_memory()              — hard delete (remove slice from store entirely)

  Use reset when the parent or admin wants to start fresh but the account continues.
  Use delete for account closure, right-to-erasure requests, and test cleanup.

PATTERN MATCHING DESIGN
-----------------------
  Word-boundary regex (\b...\b) is used instead of simple substring matching.
  This prevents false positives on legitimate educational words:
    "automorphism" is NOT matched by the "autism" pattern ✓
    "the Great Depression" is NOT matched (see note below on "depression")
    "bipolar coordinates" is NOT matched by "bipolar disorder" ✓

  Patterns are phrased specifically enough to avoid blocking legitimate educational
  vocabulary. Single common words are avoided when they have legitimate educational
  meanings — only clinical/diagnostic phrasings are blocked.

  False positives to monitor (Phase 3 may add a reporting/audit log):
    - New curriculum topics that happen to share substrings with blocked terms
    - Teacher-authored labels that accidentally use clinical vocabulary

WHAT THIS MODULE DOES NOT DO
------------------------------
  - Does NOT implement a full GDPR compliance workflow
  - Does NOT implement a full audit log (deferred to Phase 3)
  - Does NOT validate content from outside the AI service boundary
    (API-level validation is a Phase 3 concern — see TutorController)
  - Does NOT score or rank content quality — only blocks clearly unsafe patterns
  - Does NOT replace the need for human review of learner memory content

DEFERRED TO PHASE 3
--------------------
  - Audit log for reset/delete operations (with actor, timestamp, scope)
  - Scheduled deletion job for GDPR right-to-erasure requests
  - API boundary validation (guard runs in LearnerMemoryService, not at HTTP layer yet)
  - Parent-facing reset/delete UI and backend endpoint
  - Tenant-scoped deletion (multi-tenant scenarios)
  - Reporting/monitoring for guardrail violations (currently silent reject + raise)
"""
from __future__ import annotations

import re
from dataclasses import dataclass
from enum import Enum
from typing import Sequence

from app.models.learner_memory import MisconceptionObservation, WeakTopicObservation


# ── Reset scope ────────────────────────────────────────────────────────────────

class LearnerMemoryResetScope(str, Enum):
    """
    The scope of a learner memory reset operation.

    Passed to LearnerMemoryService.reset_memory() to specify which part of the
    learner profile should be cleared.

    ORDERING NOTE: When a full wipe is needed, use ALL rather than chaining
    individual scopes. ALL guarantees a single consistent store write.
    """

    SESSION_PENDING = "session_pending"
    """
    Clear only session-local pending observations for this user.
    The persisted LearnerMemorySlice is NOT modified by this scope.
    Use at the end of a tutor session to discard observations that never
    reached a promotion threshold.
    """

    TOPIC_SIGNALS = "topic_signals"
    """
    Clear weak_topics and observed_misconceptions from the slice.
    Also clears related pending entries (weak_topics, misconceptions).
    Preserves preferences (explanation_style, pace_signal).
    Use when the learner's academic context has changed significantly
    (e.g. subject change, re-enrollment after a long break).
    """

    PREFERENCES = "preferences"
    """
    Clear explanation_style and pace_signal from the slice.
    Also clears inferred_styles pending.
    Preserves topic signals.
    Use when the learner wants to reset their stated preferences
    or when the preferences are no longer reliable.
    """

    FRICTION = "friction"
    """
    Clear recent_friction_signals from the slice.
    No pending to clear for friction (friction goes directly to the slice).
    Use for housekeeping or at the start of a new academic period.
    """

    ALL = "all"
    """
    Clear ALL memory signals from the slice and ALL pending entries.
    The LearnerMemorySlice record itself remains in the store (now empty).
    Use for parent/admin-requested full reset while the account continues.
    For account closure or GDPR erasure, use delete_user_memory() instead.
    """


# ── Guardrail violation ────────────────────────────────────────────────────────

@dataclass(frozen=True)
class GuardrailViolation:
    """
    A single guardrail violation detected during content validation.

    Immutable. Multiple violations may be produced from a single update input —
    all are collected before raising LearnerMemoryGuardrailError.
    """

    field: str
    """The field name that failed validation (e.g. 'topic_label', 'description')."""

    reason: str
    """Human-readable explanation of why the content was rejected."""

    rejected_value: str
    """The value that was rejected. Truncated to 100 chars if necessary."""


class LearnerMemoryGuardrailError(Exception):
    """
    Raised by LearnerMemoryService.apply_update() when submitted observation
    content violates learner memory safety guardrails.

    This is NOT a user input error. It signals that code is attempting to store
    educationally inappropriate or child-unsafe content in the learner profile.
    The calling code must:
      1. Log this as a WARNING (not ERROR — the platform continues running)
      2. NOT store any memory from the affected update
      3. NOT surface the specific violation detail to the end user

    Because this exception is raised before any state changes, the learner
    memory slice is guaranteed to be unmodified when this is raised.

    Attributes:
        violations: The list of individual GuardrailViolation objects.
    """

    def __init__(self, violations: list[GuardrailViolation]) -> None:
        self.violations = violations
        details = "; ".join(
            f"{v.field}: {v.reason} (value={v.rejected_value!r})"
            for v in violations
        )
        super().__init__(f"Learner memory guardrail violation(s): {details}")


# ── Forbidden content pattern groups ──────────────────────────────────────────
#
# ADDING PATTERNS: Add to the relevant frozenset. Use full clinical phrasings
# rather than single common words to minimise false positives on legitimate
# curriculum vocabulary. Each group must have a clear reason string.
#
# WORD-BOUNDARY MATCHING: All patterns use \b...\b so that legitimate vocabulary
# sharing prefixes/suffixes is not accidentally blocked.
# Example: "autism" pattern does NOT match "automorphism" ✓

_DIAGNOSTIC_PATTERNS: frozenset[str] = frozenset({
    "adhd",
    "attention deficit",
    "attention deficit hyperactivity",
    "autism",
    "autistic",
    "asd",
    "asperger",
    "dyslexia",
    "dyslexic",
    "dyscalculia",
    "dyspraxia",
    "learning disability",
    "learning disabilities",
    "learning disorder",
    "intellectual disability",
    "cognitive impairment",
    "processing disorder",
    "sensory processing disorder",
    "developmental delay",
    "special needs diagnosis",
    "iep student",
    "504 plan",
})
"""
Medical and educational diagnostic labels.

These must never appear in topic_label or misconception description fields.
A child's educational history must not record medical diagnoses as memory facts —
this is a child safety requirement, not an engineering preference.

Note: "special needs" alone is not blocked (too broad and sometimes appropriate
in non-diagnostic educational contexts). "special needs diagnosis" is blocked
because it asserts a clinical diagnosis.
"""

_PSYCHOLOGICAL_PATTERNS: frozenset[str] = frozenset({
    "anxiety disorder",
    "generalized anxiety disorder",
    "social anxiety",
    "panic disorder",
    "clinical depression",
    "major depressive disorder",
    "depressive disorder",
    "traumatized",
    "trauma response",
    "complex trauma",
    "ptsd",
    "post-traumatic stress",
    "bipolar disorder",
    "bipolar",
    "schizophrenia",
    "obsessive compulsive",
    "ocd",
    "mental health disorder",
    "emotional disorder",
    "behavioral disorder",
    "psychiatric diagnosis",
    "psychological disorder",
    "dissociative",
})
"""
Psychological and psychiatric claims.

Learner memory must not record mental health inferences about children.

IMPORTANT: Common educational terms are intentionally NOT blocked here.
  Allowed: "frustrated", "confused", "anxious about fractions" (situational)
  Blocked: "anxiety disorder", "clinical depression" (clinical/diagnostic phrasings)

This distinction preserves the ability to record observations like
"expressed frustration during mixed-number lesson" while blocking
psychiatric labeling.
"""

_ABILITY_RANKING_PATTERNS: frozenset[str] = frozenset({
    "dumb",
    "stupid",
    "idiot",
    "moron",
    "imbecile",
    "slow learner",
    "low ability student",
    "low iq",
    "below average ability",
    "intellectually inferior",
    "remedial student",
    "cannot learn",
    "incapable of learning",
    "will never understand",
    "unteachable",
    "hopeless student",
})
"""
Ability-ranking and derogatory language.

These are never acceptable in any educational observation about a child.
A tutor should describe specific observable difficulty with specific content —
never rank or label the learner's general ability or intelligence.
"""

_ENGAGEMENT_MANIPULATION_PATTERNS: frozenset[str] = frozenset({
    "addiction score",
    "engagement addiction",
    "compulsive behavior score",
    "dopamine loop",
    "behavioral addiction",
    "engagement manipulation",
})
"""
Engagement manipulation signals.

Learner memory is for educational observations, not behavioral engagement metrics.
No addiction-scoring, dopamine-loop analysis, or manipulation-oriented signals
should ever enter the learner profile.
"""

# Compiled pattern table: each entry is (compiled_regex, reason_string).
# The reason string is included verbatim in GuardrailViolation.reason.
_ALL_PATTERN_GROUPS: tuple[tuple[frozenset[str], str], ...] = (
    (_DIAGNOSTIC_PATTERNS, "diagnostic label not permitted in learner memory"),
    (_PSYCHOLOGICAL_PATTERNS, "psychological claim not permitted in learner memory"),
    (_ABILITY_RANKING_PATTERNS, "ability-ranking language not permitted in learner memory"),
    (_ENGAGEMENT_MANIPULATION_PATTERNS, "engagement manipulation signal not permitted in learner memory"),
)


def _compile_group(patterns: frozenset[str]) -> re.Pattern[str]:
    """
    Compile a frozenset of patterns into a single word-boundary regex.

    Sorts longest-first so that more specific multi-word patterns are checked
    before shorter ones that might be substrings of them.
    """
    sorted_patterns = sorted(patterns, key=len, reverse=True)
    escaped = [re.escape(p) for p in sorted_patterns]
    return re.compile(r"\b(" + "|".join(escaped) + r")\b", re.IGNORECASE)


_COMPILED_GROUPS: tuple[tuple[re.Pattern[str], str], ...] = tuple(
    (_compile_group(group), reason)
    for group, reason in _ALL_PATTERN_GROUPS
)


# ── Safety guard ───────────────────────────────────────────────────────────────

class LearnerMemorySafetyGuard:
    """
    Content-level safety guardrail for learner memory observations.

    This is an explicit, code-level enforcement layer — independent of prompt
    wording and independent of LLM provider behaviour.

    Validates that no diagnostic labels, psychological claims, ability-ranking
    language, or engagement manipulation signals enter the learner memory store.
    These guardrails apply to ALL observation text fields regardless of source.

    Because this class is stateless, a module-level singleton is provided via
    the module-level convenience functions check_topic_label() and
    check_description(). LearnerMemoryService also instantiates one internally.

    Thread-safety: LearnerMemorySafetyGuard is fully stateless and safe to share.
    """

    def check_topic_label(self, label: str) -> GuardrailViolation | None:
        """
        Check a WeakTopicObservation.topic_label for forbidden content.

        Returns a GuardrailViolation if any forbidden pattern is found,
        None if the label is safe.

        This only checks content safety — length/type validation is handled
        by Pydantic in WeakTopicObservation.
        """
        return self._check_text(label, "topic_label")

    def check_description(self, description: str) -> GuardrailViolation | None:
        """
        Check a MisconceptionObservation.description for forbidden content.

        Returns a GuardrailViolation if any forbidden pattern is found,
        None if the description is safe.
        """
        return self._check_text(description, "description")

    def validate_update_observations(
        self,
        weak_topics: Sequence[WeakTopicObservation],
        misconceptions: Sequence[MisconceptionObservation],
    ) -> list[GuardrailViolation]:
        """
        Validate all topic labels and misconception descriptions in a batch.

        Returns a list of all violations found. Returns an empty list if all
        content is safe.

        USAGE IN APPLY_UPDATE:
          Call this BEFORE applying any changes to the memory store.
          If the returned list is non-empty, raise LearnerMemoryGuardrailError
          and do NOT apply any part of the update. This preserves atomicity —
          either the entire update is applied or nothing is.
        """
        violations: list[GuardrailViolation] = []
        for obs in weak_topics:
            v = self.check_topic_label(obs.topic_label)
            if v is not None:
                violations.append(v)
        for obs in misconceptions:
            v = self.check_description(obs.description)
            if v is not None:
                violations.append(v)
        return violations

    def _check_text(self, text: str, field: str) -> GuardrailViolation | None:
        """Check text against all compiled pattern groups. Return first violation found."""
        for compiled, reason in _COMPILED_GROUPS:
            match = compiled.search(text)
            if match is not None:
                truncated = text[:100] + "..." if len(text) > 100 else text
                return GuardrailViolation(
                    field=field,
                    reason=reason,
                    rejected_value=truncated,
                )
        return None


# ── Module-level singleton and convenience functions ───────────────────────────

_default_guard = LearnerMemorySafetyGuard()


def check_topic_label(label: str) -> GuardrailViolation | None:
    """
    Check a topic label against all learner memory safety guardrails.

    Convenience wrapper around the module-level LearnerMemorySafetyGuard singleton.
    Returns a GuardrailViolation if the label is unsafe, None if it is safe.
    """
    return _default_guard.check_topic_label(label)


def check_description(description: str) -> GuardrailViolation | None:
    """
    Check a misconception description against all learner memory safety guardrails.

    Convenience wrapper around the module-level LearnerMemorySafetyGuard singleton.
    Returns a GuardrailViolation if the description is unsafe, None if it is safe.
    """
    return _default_guard.check_description(description)
